### ISSUE TITLE
Casesensitive Anmeldung per E-Mail-Adresse

### ISSUE THREAD

**Issue by basistom** [terminal42/contao-mailusername#14]
Wir haben auf einer Website festgestellt, dass die Anmeldung mittels E-Mail-Adresse casesensitiv ist, was für viele Benutzer, die Ihre E-Mail-Adresse bei der Anmeldung mit beginnenden Großbuchstaben geschrieben haben, sich dann nicht mehr anmelden konnten. Aus meiner Sicht ist es sinnvoll E-Mail-Adressen Case-Insensitve zu behandeln. Ließe sich das anpassen?

**Comment by richardhj** [comment]
Fixed in 1.0.7.
