### ISSUE TITLE
E-Mail-Adresse nötig trotzt deaktiviertem Login

### ISSUE THREAD

**Issue by manjarco** [terminal42/contao-mailusername#15]
Das Mitglied-Formular im BE erwartet eine E-Mail-Adresse obwohl der Login für das Mitglied nicht aktiviert wurde (also auch kein Benutzername gefordert ist).

Fehlermeldung:
`An exception occurred while executing 'UPDATE tl_member SET username='' WHERE id='57'': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'username'`

<img width="884" alt="Bildschirmfoto 2019-06-10 um 18 11 48" src="https://user-images.githubusercontent.com/274524/59209360-6dd73680-8bab-11e9-9127-5060eba931bb.png">

**Comment by richardhj** [comment]
Mail-Adresse ist ja standardmäßig mandatory?

**Comment by richardhj** [comment]
In case you disabled `mandatory` for email, I would recommend to set `doNotSaveEmpty` to true. Does this fix the issue?

**Comment by richardhj** [comment]
You can also try to `unset($GLOBALS['TL_DCA']['tl_member']['config']['sql']['keys']['email'])`.

**Comment by manjarco** [comment]
heimrichhannot/contao-member_plus disabled `mandatory` for email for me ;)

Both your ideas didn't fix the problem for me. I also tried setting `$GLOBALS['TL_DCA']['tl_member']['fields']['username']['eval']['unique'] = false;` 

But because its a problem with my specific configuration I will find a solution myself. Thanks anyway.

**Comment by aschempp** [comment]
I think this should be fixed in this bundle. We should only write to the username field if the email value is not empty, and/or if the email field is empty it should set the username to NULL

**Comment by richardhj** [comment]
Fixed in eab89afa8ae7fc71373e9e38365fd1a8b6f284c2.
