### ISSUE TITLE
The server returned a "401 Unauthorized".

### ISSUE THREAD

**Issue by swinde** [terminal42/contao-mailusername#16]
Hallo, ich habe dieses Modul erfolgreich getestet, vielen Dank dafür.
Allerdings ist mir ein Problem aufgefallen!

Man kann eigentlich einem Member nicht erlauben, die Emailadresse zu editieren, da er sich selbst dabei den Ast absägt auf dem er sitzt. Da er nach der Änderung nicht mehr berechtigt ist die geschützte Seite zu sehen! Die E-Mail-Adresse und damit der Benutzername wird richtig geändert. Beim Daten speichern kommt es zur Fehlermeldung The server returned a "401 Unauthorized".
Kann man das irgendwie abfangen?
Viele Grüße
Steffen Winde

**Comment by aschempp** [comment]
Warum ist er nach der Änderung nicht mehr berechtigt? Wird er automatisch abgemeldet? Welche Contao-Version verwendest du?

**Comment by swinde** [comment]
Guten Morgen, hach das passiert mir immer wieder! 
Hier die Versionsangaben: Contao Version 4.7.7
Ich habe mich im Frontend angemeldet und über das Modul "Personendaten" wurde das Passwort geändert und dann kam der Fehler! 
Jetzt wollte ich den Fehler noch einmal nachstellen und jetzt wird direkt nach der Änderung richtig zum Loginformular geleitet.
Ich glaube der Issue kann geschlossen werden. Ich mache es gleich mal selbst.
Danke für die Rückmeldung!

**Comment by aschempp** [comment]
Wohl auf jeden Fall kein Problem dieser Erweiterung. Ich würde aber auch vermuten dass der Logout in einer neueren Contao-Version nicht mehr auftritt.

**Comment by swinde** [comment]
Funktioniert jetzt auch mit der Contao Version. Keine Ahnung was das war!
