### ISSUE TITLE
E-Mail scheinbar nicht mehr Unique

### ISSUE THREAD

**Issue by hh-com** [terminal42/contao-mailusername#22]
2.0.1
Wenn ein bestehender Datensatz gespeichert wird, kommt die Meldung "Eintrag existiert bereits" bei der E-Mail Adresse.
Der Datensatz existiert aber kein 2tes Mal.

2.0.0
Ein bestehender Datensatz kann ohne Probleme gespeichert werden.

**Comment by eBlick** [comment]
Kann ich ebenfalls bestätigen.
Änderungen am Datensatz werden gespeichert.
Allerdings kommt jedesmal eine Fehlermeldung, dass die E-Mail Adresse bereits existiert.
Contao 4.13.5 mail-to-username Version 2.0.1

**Comment by fritzmg** [comment]
Should be fixed by #23

**Comment by markaba** [comment]
Kann ich bestätigen, Fehler ist bei mir behoben. Vielen Dank!

**Comment by eBlick** [comment]
Auch hier positive Bestätigung.

**Comment by aschempp** [comment]
fixed in bf5789c9e5fdd3084a8c31502f91da09d45fe78c
