### ISSUE TITLE
Warning on `fields.email.save` callback in front end

### ISSUE THREAD

**Issue by ameotoko** [terminal42/contao-mailusername#25]
This gives a `Warning: Attempt to read property "id" on null`, because `$dc` is `null` in frontend:

https://github.com/terminal42/contao-mailusername/blob/10e8026e5363cd78c95cee54018fb6bf168d1dad/src/EventListener/MailUsernameListener.php#L58-L62

![Screenshot 2022-07-26 at 19 47 09](https://user-images.githubusercontent.com/10257912/181075830-89e6a7c0-0488-4934-99b0-d6cb566e6a01.png)

**Comment by aschempp** [comment]
fixed in 426aa78d23f36cf1d57c49a4f1c5cabb18171669
