### ISSUE TITLE
Fehlerhafte Übersetzung bei Einsatz des Newsletter Moduls

### ISSUE THREAD

**Issue by Total-Reality** [terminal42/contao-mailusername#9]
Hi Andreas

In der Datei system\modules\mailusername\languages\en\default.php stimmt irgendwas nicht.
Und das komische ist, dass meine Website nur auf Deutsch ist und die englische Sprachdatei Auswirkungen auf die Deutsche Seite hat.

Die folgende Angabe scheint mir falsch zu sein:
$GLOBALS['TL_LANG']['MSC']['username'] = &$GLOBALS['TL_LANG']['MSC']['emailAddress'];

Das bewirkt nämlich, dass dann als Platzhalter für die Angabe der E-Mail-Adresse im Newsletter Modul folgendes steht: "Benutzername". Da muss aber stehen "E-Mail-Adresse".
Wenn ich die Deklarierung entferne oder mailusername deaktiviere, funktioniert es korrekt.

Viele Grüße
Christian

**Comment by CodeAlDente** [comment]
Is there a link between this problem and the ticket #10?

**Comment by Total-Reality** [comment]
I think that it is the same!
